
MapSeven:
  Gallery:
    imageClassName: img-responsive
    presets:
      preview:
        maximumWidth: 680
        maximumHeight: 453
        allowCropping: true
        allowUpScaling: true
      lightbox:
        maximumWidth: 640
        maximumHeight: 480
        allowCropping: false
        allowUpScaling: false
      tagCarousel:
        maximumWidth: 200
        maximumHeight: 100
        allowCropping: true
        allowUpScaling: true
Neos:
  Neos:
    nodeTypes:
      groups:
        gallery:
          position: 'after plugins'
          label: Gallery
    fusion:
      autoInclude:
        MapSeven.Gallery: true
